name: Frontend CI/CD

on:
  push:
    branches:
      - main
      - deploy/production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run tests with coverage
        working-directory: ./frontend
        run: npm test

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./frontend/coverage

  deliver:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        working-directory: ./frontend
        run: docker build -t my-frontend-app .

      - name: Login to Docker Hub
        env:
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        run: echo "${DOCKER_HUB_TOKEN}" | docker login -u "${DOCKER_HUB_USERNAME}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker tag my-frontend-app ${{ secrets.DOCKER_HUB_USERNAME }}/my-frontend-app:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-frontend-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        env:
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        run: echo "${DOCKER_HUB_TOKEN}" | docker login -u "${DOCKER_HUB_USERNAME}" --password-stdin

      - name: Pull Docker image from Docker Hub
        run: docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/my-frontend-app:latest

      - name: Run Docker container
        run: docker run -d -p 80:80 --name my-frontend-app ${{ secrets.DOCKER_HUB_USERNAME }}/my-frontend-app:latest

      - name: Check Docker container status
        run: docker ps

      - name: Check Docker container logs
        run: docker logs my-frontend-app
