name: Frontend CI/CD

on:
  push:
    branches:
      - main
      - deploy/production

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Linting Placeholder
        run: echo "Linting code... (This is a placeholder step)"

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Testing Placeholder
        run: echo "Running tests... (This is a placeholder step)"

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run tests
        working-directory: ./frontend
        run: npm test

      - name: Build Docker image
        working-directory: ./frontend
        run: docker build -t my-frontend-app:latest .

  deliver:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        env:
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        run: echo "${DOCKER_HUB_TOKEN}" | docker login -u "${DOCKER_HUB_USERNAME}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker tag my-frontend-app:latest ${{ secrets.DOCKER_HUB_USERNAME }}/my-frontend-app:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-frontend-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        env:
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        run: echo "${DOCKER_HUB_TOKEN}" | docker login -u "${DOCKER_HUB_USERNAME}" --password-stdin

      - name: Pull Docker image from Docker Hub
        run: docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/my-frontend-app:latest

      - name: Run Docker image
        run: docker run -d -p 80:80 ${{ secrets.DOCKER_HUB_USERNAME }}/my-frontend-app:latest
